version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admintest
    ports:
      - "3306:3306"
    volumes:
      - ./app/backend/database:/docker-entrypoint-initdb.d