---
- name: Deploy Vue, Node.js, and MySQL Docker containers
  hosts: remote
  become: true
  vars:
    vue_image: 'twetch/frontend-library:latest' # Replace with your Vue app image
    node_image: 'twetch/backend-library:latest' # Replace with your Node.js app image
    mysql_image: 'mysql:8.0' # MySQL image
    db_container_name: 'mysql_db'
    db_volume: '/home/maxime/volume/mysql'
    db_user: 'root' # Set database user
    db_password: 'password' # Set database password
    db_name: 'library_manager'
    init_sql: '/tmp/init.sql'
    secret_key: 'coucou' # Set database name
    pip_package_requirements:
      - "requests"

  tasks:
    - name: Check if Docker is already installed
      ansible.builtin.command: docker --version
      register: docker_check
      ignore_errors: true

    - name: Install Docker if not present
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: true
      when: docker_check.rc != 0

    - name: Create a custom Docker network
      community.docker.docker_network:
        name: app_network
        driver: bridge
        state: present

    - name: Pull Vue image
      community.docker.docker_image:
        name: '{{ vue_image }}'
        source: pull

    - name: Pull Node.js image
      community.docker.docker_image:
        name: '{{ node_image }}'
        source: pull

    - name: Pull MySQL image
      community.docker.docker_image:
        name: '{{ mysql_image }}'
        source: pull

    - name: Run MySQL container
      community.docker.docker_container:
        name: '{{ db_container_name }}'
        image: '{{ mysql_image }}'
        env:
          MYSQL_ROOT_PASSWORD: '{{ db_password }}'
          MYSQL_PASSWORD: '{{ db_password }}'
          MYSQL_DATABASE: '{{ db_name }}'
        networks:
          - name: app_network
        ports:
          - '3306:3306'
        volumes:
          - '{{ db_volume }}:/var/lib/mysql'
          - '{{ init_sql }}:/docker-entrypoint-initdb.d/init.sql'
        restart_policy: always

    - name: Run Node.js container
      community.docker.docker_container:
        name: 'node_app'
        image: '{{ node_image }}'
        networks:
          - name: app_network
        ports:
          - '3000:3000'
        restart_policy: always
        env:
          DB_HOST: 'mysql_db' # Reference MySQL container by name
          DB_USER: '{{ db_user }}'
          DB_PASS: '{{ db_password }}'
          DB_SCHEMA: '{{ db_name }}'
          SECRET_KEY: '{{ secret_key }}' # Set secret key

    - name: Run Vue container
      community.docker.docker_container:
        name: 'vue_app'
        image: '{{ vue_image }}'
        ports:
          - '4173:4173'
        restart_policy: always
