name: Build and Push Docker Backend Image to GitHub Container Registry

on:
  push:
    branches:
      - add_github_automation  # Adjust as needed
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Docker_build

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker backend image
        uses: docker/build-push-action@v4
        with:
          context: app/frontend/library_manager
          file: app/frontend/library_manager/Dockerfile  # Specify the Dockerfile path here
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/frontend-library:latest