name: Build and Push Docker Backend Image to GitHub Container Registry

on:
  push:
    branches:
      - add_github_automation  # Adjust as needed
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test secrets
        run: echo " ${{secrets.GITHUB_TOKEN}} is available now"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: "maxgre42160@gmail.com"
          password: "#Dark42160"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker backend image
        uses: docker/build-push-action@v4
        with:
          context: app/backend
          file: Dockerfile  # Specify the Dockerfile path here
          push: true
          tags: maxgrc/backend-library:latest
