name: Build and Push Docker Backend Image to GitHub Container Registry

on:
  push:
    branches:
      - main  # Adjust as needed
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test secrets
        run: echo " ${{secrets.GITHUB_TOKEN}} is available"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker backend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./app/backend/Dockerfile  # Specify the Dockerfile path here
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/backend:latest
